### ISSUE TITLE
No module named fabtools.files

### ISSUE THREAD

**Issue by d3netxer** [state-hiu/ittc-fabric#1]
Tried running fabric got this ImportError:

hiu@gambit:~/repos/ittc-fabric$ fab tileserver_frontend add_cache
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/fabric/main.py", line 658, in main
    docstring, callables, default = load_fabfile(fabfile)
  File "/usr/lib/python2.7/dist-packages/fabric/main.py", line 165, in load_fabfile
    imported = importer(os.path.splitext(fabfile)[0])
  File "/home/hiu/repos/ittc-fabric/fabfile.py", line 6, in <module>
    from fabtools.files import is_file, is_dir, md5sum
ImportError: No module named fabtools.files

**Comment by state-hiu-dev** [comment]
Added install instructions to readme.
